version: "3.4"
services:
  bot:
    build:
      context: https://github.com/reef-defi/reefswap.git
    image: reefswap-bot
    command: node scripts/trading-bot/runner.js
    environment:
      - MINUTE_INTERVAL=${MINUTE_INTERVAL}
      - MNEMONIC_TESTNET=${MNEMONIC_TESTNET}
      - MNEMONIC_MAINNET=${MNEMONIC_MAINNET}
      - MNEMONIC_LOCALHOST=${MNEMONIC_LOCALHOST}